# app.R
library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)
library(bslib)
library(scales)
library(bsicons)
library(rstanarm)
library(DT)
library(INLA)

source("baci_analysis_functions.R")

# Configuration for survey methods
survey_methods_params <- tribble(
  ~Method,                   ~SD_Precision,
  "Benthic Photo Transects", 0.045,
  "RHIS (Rapid Survey)",     0.120,
  "Detailed Orthomosaic",    0.020,
  "ReefScan (AI Towed)",     0.035
)

# This must be defined globally for the UI selector
METRIC_DEFINITIONS <- tribble(
  ~Metric,                ~Mean_Baseline, ~Temporal_SD,
  "Coral Cover",          0.30,           0.04,
  "Structural Complexity",0.40,           0.05,
  "Algal Cover",          0.20,           0.06,
  "Fish Biomass",         0.50,           0.08,
  "Fish Diversity",       0.60,           0.07,
  "Invertebrate Density", 0.35,           0.09
)

ui <- page_navbar(
  title = "BACI Credit Simulator",
  theme = bs_theme(version = 5, preset = "shiny"),
  
  tabPanel("BACI Analysis & Crediting",
           page_sidebar(
             sidebar = sidebar(
               width = "350px",
               tags$h4("Simulation Controls"),
               selectInput("sim_method", "Survey Method", choices = survey_methods_params$Method, selected = "Benthic Photo Transects"),
               sliderInput("sim_nctrl", "Number of Control Sites", min = 1, max = 10, value = 5, step = 1),
               sliderInput("sim_ntran", "Number of Transects per Site", min = 1, max = 10, value = 5, step = 1),
               tags$hr(),
               sliderInput("sim_nyears", "Monitoring Duration (Years)", min = 5, max = 20, value = 10, step = 1),
               sliderInput("sim_intervention_year", "Intervention Start Year", min = 1, max = 20, value = 3, step = 1),
               numericInput("sim_uplift_pct", "True Annual Uplift Post-Intervention (%)", value = 5, min = 0, max = 20, step = 1),
               tags$hr(),
               selectInput("sim_shock_type", "Exogenous Shock Scenario",
                           choices = c("No Shock", "Cyclonic Impact", "Bleaching Event", "Localized Impact")),
               sliderInput("sim_shock_year", "Shock Event Year", min = 1, max = 20, value = 7, step = 1),
               sliderInput("sim_shock_magnitude", "Shock Magnitude (% Loss)", min = 0, max = 100, value = 50, step = 5),
               tags$hr(),
               numericInput("sim_sd_spatial", "Spatial Patchiness (SD)", value = 0.03, min = 0.01, max = 0.2, step = 0.01),
               numericInput("sim_sd_temporal", "Residual Temporal SD", value = 0.04, min = 0.01, max = 0.2, step = 0.01),
               tags$hr(),
               radioButtons("analysis_method", "Analysis Method", 
                            choices = c("Full Bayesian (Stan)", "Fast Approximation (INLA)"), 
                            selected = "Fast Approximation (INLA)"),
               actionButton("run_sim", "Run Analysis", class = "btn-primary w-100", icon = icon("play"))
             ),
             
             layout_columns(
               col_widths = c(4, 4, 4),
               value_box(title = "Mean Annual Uplift (Composite)", value = textOutput("uplift_card"), showcase = bs_icon("graph-up-arrow")),
               value_box(title = "Probability of Uplift (Composite)", value = textOutput("prob_card"), showcase = bs_icon("patch-check-fill")),
               value_box(title = "Final Credit Score (Composite)", value = textOutput("credit_card"), showcase = bs_icon("award-fill"), theme_color = "success")
             ),
             layout_columns(
               col_widths = c(7, 5),
               card(
                 card_header(
                   class = "d-flex justify-content-between align-items-center",
                   "Simulated Metric Trends",
                   selectInput("metric_selector", NULL, choices = c("Composite Index", METRIC_DEFINITIONS$Metric), selected = "Composite Index", width = "250px")
                 ),
                 plotOutput("simulationPlot", height = "400px")
               ),
               card(
                 card_header("Detailed Results by Metric"),
                 DTOutput("resultsTable")
               )
             )
           )
  ),
  
  tabPanel("Simulated Raw Data",
           card(
             card_header("Raw Simulated Transect-Level Data"),
             card_body(
               p("This table shows the complete raw dataset generated by the simulation. Use the filters at the top of each column to explore the data and diagnose how shock events affect specific sites and years."),
               DTOutput("simulatedDataTable")
             )
           )
  )
)

server <- function(input, output, session) {
  
  observeEvent(input$sim_nyears, {
    nyears <- input$sim_nyears
    updateSliderInput(session, "sim_intervention_year", max = nyears, value = min(input$sim_intervention_year, nyears))
    updateSliderInput(session, "sim_shock_year", max = nyears, value = min(input$sim_shock_year, nyears))
  })
  
  analysis_results <- eventReactive(input$run_sim, {
    msg <- if(input$analysis_method == "Full Bayesian (Stan)") "Running full Bayesian simulation... this will be slow." else "Running fast approximation..."
    showNotification(msg, type = "message", duration = 10)
    
    method_params <- survey_methods_params %>% filter(Method == input$sim_method)
    sd_precision <- method_params$SD_Precision
    
    run_baci_analysis(
      analysis_method = input$analysis_method,
      n_sites_ctrl = input$sim_nctrl,
      n_transects = input$sim_ntran,
      n_years = input$sim_nyears,
      intervention_year = input$sim_intervention_year,
      true_uplift_pct = input$sim_uplift_pct,
      shock_type = input$sim_shock_type,
      shock_year = input$sim_shock_year,
      shock_magnitude_pct = input$sim_shock_magnitude,
      survey_precision_sd = sd_precision,
      spatial_patchiness_sd = input$sim_sd_spatial,
      temporal_variation_sd = input$sim_sd_temporal
    )
  })
  
  output$uplift_card <- renderText({ req(analysis_results()); paste0(round(analysis_results()$composite_uplift * 100, 2), "%") })
  output$prob_card <- renderText({ req(analysis_results()); scales::percent(analysis_results()$composite_prob, accuracy = 0.1) })
  output$credit_card <- renderText({ req(analysis_results()); round(analysis_results()$composite_credit * 100, 1) })
  
  output$simulationPlot <- renderPlot({
    req(input$metric_selector)
    plot_data <- analysis_results()$plot_data %>%
      filter(Metric == input$metric_selector)
    
    y_label <- if (input$metric_selector == "Composite Index") "Reef Condition Index (Normalized)" else input$metric_selector
    y_limits <- if (input$metric_selector == "Composite Index") c(0.5, 1.5) else c(0, 1)
    y_formatter <- if (input$metric_selector == "Composite Index") scales::number_format(accuracy = 0.1) else scales::percent
    
    p <- ggplot(plot_data, aes(x = Year, y = Mean, color = Site_Type, fill = Site_Type)) +
      geom_vline(xintercept = input$sim_intervention_year, linetype = "dashed", color = "blue", linewidth = 1) +
      geom_ribbon(aes(ymin = Lower_CI, ymax = Upper_CI), alpha = 0.2, linetype = 0) +
      geom_line(linewidth = 1.2) +
      annotate("text", x = input$sim_intervention_year, y = y_limits[2], label = "Intervention", color = "blue", hjust = -0.1, vjust = 1) +
      coord_cartesian(ylim = y_limits, expand = FALSE) + scale_y_continuous(labels = y_formatter, name = y_label) +
      scale_color_manual(values = c("Treatment" = "darkorange", "Control" = "gray40")) + scale_fill_manual(values = c("Treatment" = "darkorange", "Control" = "gray40")) +
      labs(title = paste("Simulated Trend for:", input$metric_selector), subtitle = paste("Design:", input$sim_nctrl, "Control Sites,", input$sim_ntran, "Transects/Site,", "using", input$sim_method), color = "Site Type", fill = "Site Type") +
      theme_minimal(base_size = 14) + theme(legend.position = "bottom")
    
    if (input$sim_shock_type != "No Shock") {
      p <- p + 
        geom_vline(xintercept = input$sim_shock_year, linetype = "dashed", color = "red", linewidth = 1) +
        annotate("text", x = input$sim_shock_year, y = y_limits[2] * 0.95, label = "Shock Event", color = "red", hjust = -0.1, vjust = 1)
    }
    
    p
  })
  
  output$resultsTable <- renderDT({
    results_data <- analysis_results()$results_table
    
    results_data <- results_data %>%
      mutate(Uplift_CI = paste0(round(Uplift_CI_Lower * 100, 1), "% to ", round(Uplift_CI_Upper * 100, 1), "%")) %>%
      select(Metric, Mean_Uplift, Uplift_CI, Prob_Real_Uplift, Credit_Score)
    
    DT::datatable(
      results_data,
      rownames = FALSE,
      colnames = c("Metric", "Mean Annual Uplift", "95% CI of Uplift", "Probability of Uplift", "Credit Score"),
      options = list(dom = 't', pageLength = 10, scrollX = TRUE)
    ) %>%
      formatPercentage(c("Mean_Uplift", "Prob_Real_Uplift"), digits = 1) %>%
      formatRound("Credit_Score", digits = 2)
  })
  
  output$simulatedDataTable <- renderDT({
    req(analysis_results())
    raw_data <- analysis_results()$raw_data
    
    DT::datatable(
      raw_data,
      filter = 'top',
      rownames = FALSE,
      options = list(pageLength = 10, scrollX = TRUE)
    ) %>%
      formatPercentage(c("True_Value", "Observed_Value"), digits = 1)
  })
}

shinyApp(ui, server)